# This file is part of the COMANDO project which is released under the MIT
# license. See file LICENSE for full license details.
#
# AUTHOR: Marco Langiu

test:3.7:
  image: python:3.7
  script:
    - pip install .[pyomo,cpp-backend,linearization,test]
    - pytest -s --color=yes --durations=0 tests/


test:3.8:
  image: python:3.8
  script:
    - pip install .[pyomo,cpp-backend,linearization,test]
    - pytest -s --color=yes --durations=0 tests/
